openapi: 3.1.0
info:
  title: MK-ServerLauncher
  description: MK-ServerLauncher
  version: "VoidLand V1"
  contact:
    name: Mu_Cloud
    email: Mu_Cloud@outlook.de

servers:
  - url: http://localhost:20038/api/v1

paths:
  /server/list:
    get:
      summary: 从 MuCore 中获取服务器列表
      description: Get Server List from MuCore.
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/MuPacket'
              example:
                MP_ID: "mucore.muserver:list"
                MP_DATA:
                  serverList:
                    - "MCS1"
                    - "MCS2"
                TSS: 1145141919810

components:
  schemas:
    MuPacket:
      type: object
      properties:
        MP_ID:
          type: string
        MP_DATA:
          type: object
        TSS:
          type: number
