openapi: 3.1.0
info:
  title: MK-ServerLauncher
  description: MK-ServerLauncher
  version: VoidLad V1
  contact:
    name: Mu_Cloud
    email: Mu_Cloud@outlook.de
servers:
  - url: 'https://localhost:20038/api/v1'
paths:
  /server/list:
    get:
      summary: 从 MuCore 中获取服务器列表
      description: Get Server List from MuCore.
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MCJEServer'

components:
  schemas:
    AvailableType:
      type: "object"
      properties:
        id:
          type: "string"
        name:
          type: "string"
        desc:
          type: "string"
        api:
          type: "string"
      required:
        - "id"
        - "name"
        - "desc"
        - "api"
    JavaEnvironment:
      type: "object"
      properties:
        name:
          type: "string"
        path:
          type: "string"
        version:
          type: "string"
          default: "Unknown"
      required:
        - "name"
        - "path"
        - "version"
    Config:
      type: "object"
      properties: { }
    MCJEServer:
      type: "object"
      properties:
        name:
          type: "string"
        version:
          type: "string"
        type:
          $ref: "#/components/schemas/AvailableType"
        port:
          type: "integer"
          format: "int32"
          default: "25565"
        env:
          $ref: "#/components/schemas/JavaEnvironment"
        config:
          $ref: "#/components/schemas/Config"
        running:
          type: "boolean"
      required:
        - "name"
        - "version"
        - "type"
        - "port"
        - "env"
        - "config"
        - "running"
